init: &init
  working_directory: /home/circleci/d8
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    DEBUG: "true"
  docker:
    - image: circleci/php:7.1

version: 2
jobs:
  build:
    <<: *init
    steps:
      - checkout
      - run: echo "Init circle first build"
      - run:
          name: Config github account
          command: |
            composer config --global github-oauth.github.com $GIT_TOKEN
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_USERNAME

  deploy-acquia:
    <<: *init
    steps:
      - run:
          command: |
            ls -l
            bash scripts/deploy_to_acquia.sh

workflows:
  version: 2
  multi-build-flow:
    jobs:
      - build
      - deploy-acquia
