init: &init
  working_directory: /home/circleci/d8
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    DEBUG: "true"
  docker:
    - image: circleci/php:7.1

version: 2
jobs:
  build:
    <<: *init
    steps:
      - checkout
      - run:
          name: Config github account
          command: |
            composer config --global github-oauth.github.com $GIT_TOKEN
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_USERNAME
      - run: echo 'StrictHostKeyChecking no' > ~/.ssh/config
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/.ssh

  deploy-acquia:
    <<: *init
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: bash scripts/deploy_to_acquia.sh

workflows:
  version: 2
  multi-build-flow:
    jobs:
      - build
      - deploy-acquia:
          requires:
            - build
