init: &init
  working_directory: /home/circleci/d8
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    DEBUG: "true"
  docker:
    - image: circleci/php:7.1

version: 2
jobs:
  build:
    <<: *init
    steps:
      - checkout
      - restore_cache:
          key: composer-cache
      - run:
          name: Config github account
          command: |
            composer config --global github-oauth.github.com $GIT_TOKEN
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_USERNAME
      - run: echo 'StrictHostKeyChecking no' > ~/.ssh/config
      - run: sudo apt-get install -y libpng-dev
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd
      - run:
          name: Run composer for project
          command: sh scripts/build.sh
      - save_cache:
          key: composer-cache
          paths:
            - ~/.composer/cache
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/.ssh
            - ~/d8

  deploy-acquia:
    <<: *init
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: bash scripts/deploy_to_acquia.sh

  behat_test:
    <<: *init
    steps:
      - checkout
      - run:
          name: Install behat
          command: sh scripts/setup-behat.sh
      - run:
          name: Behat execute
          command: |
            cd test
            ls -l
            test/bin/behat

workflows:
  version: 2
  multi-build-flow:
    jobs:
      - build
      - deploy-acquia:
          requires:
            - build
      - behat_test
